# Generated by Django 3.1.6 on 2021-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imgdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=50)),
                ('bigcategory', models.CharField(max_length=50)),
                ('middlecategory', models.CharField(max_length=50)),
                ('furniturename', models.CharField(max_length=50)),
            ],
        ),
    ]
