# Generated by Django 3.1.6 on 2021-02-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
