# Generated by Django 3.1.6 on 2021-02-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_imgdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
